spring:
  application:
    name: kelvin-api
  datasource:
    url: jdbc:postgresql://localhost:5432/kelvin-db
    driver-class-name: org.postgresql.Driver
    username: kelvin_rw
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
