management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: info,health
  health:
    version-indicator:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

google-auth:
  client-id: CLIENT_ID
  enabled: false

authorization:
  # Replace the example email.
  preauthorized-admins: example@email.com

spring:
  application:
    name: kelvin-api
  datasource:
    url: jdbc:postgresql://localhost:5432/kelvin-db
    driver-class-name: org.postgresql.Driver
    username: kelvin_rw
    password: testing-password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

cors:
  origins: http://localhost:3000
