management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: info,health
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

google-auth:
  client-id: CLIENT_ID
  enabled: false

authorization:
  preauthorized-admins: douglas.lochowski.haney@gmail.com,jorge.alberto.trujillo@gmail.com,conniefritz70@gmail.com

spring:
  application:
    name: kelvin-api
  datasource:
    url: jdbc:postgresql://localhost:5432/kelvin-db
    driver-class-name: org.postgresql.Driver
    username: kelvin_rw
    password: testing-password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

cors:
  origins: http://localhost:3000
