spring:
  datasource:
    url: jdbc:postgresql://10.62.112.7:5432/kelvin-db
    driver-class-name: org.postgresql.Driver
    username: kelvin_rw
    password: __POSTGRES_PASSWORD__

google-auth:
  client-id: __OAUTH_CLIENT_ID__
  enabled: true

cors:
  origins: https://temperature-aggregator.app
