spring:
  datasource:
    url: jdbc:postgresql://10.62.112.3:5432/kelvin-db
    driver-class-name: org.postgresql.Driver
    username: kelvin_rw
    password: __POSTGRES_PASSWORD__

google-auth:
  client-id: __OAUTH_CLIENT_ID__
  enabled: true

cors:
  origins: http://localhost:3000,https://stg.temperature-aggregator.app,http://192.168.1.209.xip.io:5000
