# .github/workflows/gradle-build-pr.yml
name: Run Gradle on PRs
on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          # Version of PostgreSQL to use
          postgresql version: 11
          # POSTGRES_DB - name for the default database that is created
          postgresql db: kelvin-db
          # POSTGRES_USER - create the specified user with superuser power
          postgresql user: kelvin_rw
          # POSTGRES_PASSWORD - superuser password
          postgresql password: testing-password
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
        run: ./gradlew clean build -x composeUp -x composeDown
